apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-sync.fullname" . }}-config
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.appEnv | quote }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.env.redisPort | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  WORKERS: {{ .Values.env.workers | quote }}
  MAX_CONNECTIONS: {{ .Values.env.maxConnections | quote }}
