apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: data-sync
    repo: ../../../helm/charts
    releaseName: data-sync
    valuesFile: ../../../helm/charts/data-sync/values.production.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: data-sync
